### ISSUE TITLE
css3 属性 text-overflow 实现截取多余文字内容 以省略号来代替多余内容

### ISSUE THREAD

**Issue by zero2one3** [zero2one3/blog#5]
>觉得本文不错的，可以点个 **star** 哦～ 所有文章首发这里
>若想获取更多精选进阶好文，欢迎关注微信公众号：**前端印象**

## 前言

我们在设计网站的时候有时会遇到这样一个需求：因为页面空间大小的问题，需要将多余的文字隐藏起来，并以省略号代替，类似这样的效果：

![在这里插入图片描述](https://raw.githubusercontent.com/zero2one3/blog/main/img/20200503080836779.png)

做到这样的效果，我们需要运用两个特殊的样式来实现  text-overflow 和 white-space

## 正文
让我们分别来看一下使用了这些样式，和不使用这些样式的区别吧

- html内容
```html
<div class="box">
    <span>我是一段测试文本1我是一段测试文本2我是一段测试文本3我是一段测试文本4我是一段测试文本5我是一段测试文本5</span>
</div>
```

**1. 不使用特殊样式**
- 样式内容
```css
.box{
    background: red;
    width: 100px;
}

```
- 效果展示

![在这里插入图片描述](https://raw.githubusercontent.com/zero2one3/blog/main/img/20200503081453607.png)

我们可以看到，文本根据边框的宽度，自动换行，并且全部显示

**2. 使用 white-space: nowrap 样式**
- 样式内容
```css
.box{
    background: red;
    width: 100px;
    white-space: nowrap;             /*使文本内容不换行，写在一行*/
}
```
- 效果图
![在这里插入图片描述](https://raw.githubusercontent.com/zero2one3/blog/main/img/20200503082123696.png)

**3. 使用white-space: nowrap和overflow:hidden样式**

- 样式内容
```css
.box{
    background: red;
    width: 100px;
    white-space: nowrap;             /*使文本内容不换行，写在一行*/
    overflow: hidden;                /*隐藏多余内容*/
}
```
- 效果图
![在这里插入图片描述](https://raw.githubusercontent.com/zero2one3/blog/main/img/20200503082317650.png)

**4. 使用white-space: nowrap和overflow:hidden和text-overflow: ellipsis 样式**
- 样式内容
```css
.box{
    background: red;
    width: 100px;
    white-space: nowrap;             /*使文本内容不换行，写在一行*/
    overflow: hidden;                /*隐藏多余内容*/
    text-overflow: ellipsis;         /*将多余内容以省略号的方式展示*/
}
```
- 效果图
![在这里插入图片描述](https://raw.githubusercontent.com/zero2one3/blog/main/img/20200503082542340.png)

## 结束语
希望这篇文章对大家能有所帮助
